[package]
name = "core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] 

[dependencies]
android_logger = "0.15"
libcore = { path = "../../../../../libcore" }
jni = "0.21.1"
log = "0.4.28"
once_cell = "1.21.3"
quinn = "0.11.9"
tokio = { version = "1.48.0", features = ["full"] }
